### ISSUE TITLE
Packages folder to download to is hardcoded

### ISSUE THREAD

**Issue by delucis** [natcl/max_package_downloader#22]
As far as I can tell, Max Package Downloader functions perfectly in Max 7, except that Max 7 uses a `~/Max 7/Packages` folder by default rather than the `~/Max/Packages` that is the default in Max 6. It would be nice to have either auto-detection (if that’s possible?) of which folder is being used — as set in the Max preferences — or otherwise to have a choice of destination.

I’ll try to investigate and see if I can figure this out, but wanted to flag it here too.

Thanks!
Chris.

**Update, 23/5/2015:** All that is needed is a `; max getversion` mechanism to choose between folders for different versions of Max. See #23 for an OS X fix.

**Comment by delucis** [comment]
@emmanueljourdan Might you know of a way to directly determine the packages folder set by a user in their preferences?

**Comment by emmanueljourdan** [comment]
You could check ;max get version?

**Comment by delucis** [comment]
Hi Emmanuel, thanks!

I figured that part out (see #23), and I also just realised my question was redundant, sorry.

I mistook the option to set a custom *projects* directory as for packages. Now I see there’s no custom directory option for packages, so a `getversion` based mechanism is all that’s necessary.

Thanks,
C.

**Comment by natcl** [comment]
Hi guys, thanks for looking into this ! I haven't tested in Max 7 yet. will merge your changes !

**Comment by delucis** [comment]
Thanks Nathanaël!

If you have a Windows set-up and can check what folder Max 7 wants there, I’d be happy to implement the equivalent bit of patching if you wanted.

Best,
C.
