### ISSUE TITLE
Dependencies

### ISSUE THREAD

**Issue by delucis** [natcl/max_package_downloader#26]
Hi Nathanaël,

While using MPD — including some very successful experiences with a class of Max beginners recently — I’ve been wondering about creating a mechanism that would allow MPD to handle package dependencies ([much like npm does](https://docs.npmjs.com/files/package.json#dependencies)).

I imagine at its simplest an optional addition to the package-info.json with an array of package names:

``` json
"dependencies": [ "ejies", "Max ToolBox" ]
```

Given Max’s package system is global, declaring version ranges (like npm does) is not a possibility.

MPD could then run checks and install dependencies if not already installed or out-of-date.

More powerful, but potentially more involved in terms of implementation, would be to permit inline package declarations (using the same structure as [`max_packages_master.json`](https://github.com/natcl/max_package_downloader/blob/40abddf7599389ca33546704b4054eea1994ad61/max_packages_master.json)). Perhaps:

``` json
"dependencies": {
    "ejies": "master",
    "custom-package": {
        "link": "https://raw.githubusercontent.com/gh-user/custom-package/master/package-info.json",
        "relative_path": "None"
    }
}
```

Any thoughts? If you were enthusiastic, I’d be very happy to spend some time implementing this in MPD.

Thanks!
Chris.

**Comment by natcl** [comment]
Sorry for the late answer, as you might have seen today, Cycling has released an official package Manager so this one is not very useful anymore...  Thanks for using it while it was there though !
